steps:
- name: 'gcr.io/cloud-builders/docker'
  id: runDockerfile
  args:
  - 'build'
  - '-t'
  - 'gcr.io/cpts423seniorproject/github.com/carlyott/CIS_Docker_Repo:latest'
  - '--file=Dockerfile'
  - '.'
tags: ['testing']
images: ['gcr.io/cpts423seniorproject/github.com/carlyott/CIS_Docker_Repo:latest']
#storing artifacts in Cloud Storage (creates it in Buckets under 'Storage')
artifacts:
  objects:
    location: 'gs://testing-stk-cis/DEMO'
    #paths: ['txt.txt']
    #paths: ['report.txt', 'reportArea.txt']
    paths: ['*', '*.*']
    
